version: '2'

services:

  data-collector:
    build: ./data-collector
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment: 
      - BLUETOOTH_DEVICE_NAME=balenaHealth
    labels:
      io.balena.features.dbus: 1

  # mqtt-broker:
  #   build: ./mqtt-broker

  # connector:
  #   build: ./connector

  # influx-db:
  #   build: ./influx-db

  # dashboard:
  #   build: ./dashboard
