version: '2'

volumes:
  collected-data:
  dashboard-data:

services:
  data-collector:
    build: ./data-collector
    restart: on-failure
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1' # necessary to discover services in local mode

  eink:
    build: ./eink
    restart: on-failure
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1' # necessary to discover services in local mode

  mqtt:
    image: eclipse-mosquitto:1.6.15
    restart: always
    ports:
      - '1883:1883'

  connector:
    image: balenablocks/connector:raspberrypi3
    restart: always
    labels:
      io.balena.features.balena-api: '1' # necessary to discover services
      io.balena.features.supervisor-api: '1' # necessary to discover services in local mode
    privileged: true

  influxdb:
    image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
    restart: always
    volumes:
      - 'collected-data:/var/lib/influxdb'

  dashboard:
    image: balenablocks/dashboard
    restart: always
    volumes:
      - 'dashboard-data:/data'
    ports:
      - '80'
